language: python
python:
  - 2.7

branches:
  only:
    - master

services:
  - docker


before_install:
  - docker --version
  - sudo apt-get install -y --force-yes xfsprogs
  - sudo ./travis-builds/purge_cluster.sh
  - sudo sed -i s/^build_daemon_img/#build_daemon_img/ travis-builds/build_imgs.sh
  - sudo ./travis-builds/build_imgs.sh

install:
  - sudo ./travis-builds/prepare_osd_fs.sh
  - docker run -d --name ceph-demo -e CLUSTER=test -e NETWORK_AUTO_DETECT=4 -e CEPH_DEMO_ACCESS_KEY=G1EZ5R4K6IJ7XUQKMAED -e CEPH_DEMO_SECRET_KEY=cNmUrqpBKjCMzcfqG8fg4Qk07Xkoyau52OmvnSsz -e CEPH_DEMO_BUCKET=foobar ceph/demo

script:
  - sudo ./travis-builds/validate_demo_cluster.sh


after_failure:
  - docker images
  - docker ps
  - docker ps -a
  - docker logs ceph-demo
  - docker exec ceph-demo ceph --cluster test -s
