apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  volumes:
    - name: demo
      rbd:
        monitors:
          - "192.168.33.200:6789"
        pool: rbd
        image: demo
        user: admin
        secretRef:
          name: ceph-secret
        fsType: ext4
        readOnly: false
  containers:
  - image: busybox
    command:
      - "sleep"
      - "3600"
    volumeMounts:
    - name: demo
      mountPath: /mnt
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
