apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-config-pv 
  labels:
    img: nextcloud-config
spec:
  capacity:
    storage: 2Gi 
  accessModes:
    - ReadWriteOnce 
  rbd: 
    monitors: 
      - 192.168.33.64:6789
      - 192.168.33.65:6789
      - 192.168.33.66:6789
    pool: rbd
    image: nextcloud-config
    user: admin
    secretRef:
      name: ceph-secret 
    fsType: ext4 
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-config-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
  selector:
    matchLabels:
      img: "nextcloud-config"
