apiVersion: v1
kind: Service
metadata:
  name: ceph-board
  labels:
    name: ceph-board
spec:
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    name: ceph-board
---
kind: ReplicationController
apiVersion: v1
metadata:
  name: ceph-board
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ceph-board
    spec:
      nodeSelector:
        ceph_board: "true"
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: environment
          hostPath:
            path: /etc/environment
      containers:
        - name: ceph-board-pod
          image: cdxvirt/ceph-daemon:1.12
          args: ["board"]
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
            - name: environment
              mountPath: /etc/environment
