apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-osd
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: ceph-osd
    spec:
      hostNetwork: true
      nodeSelector:
        cdxvirt/ceph_osd: "true"
      volumes:
        - name: docker
          hostPath:
            path: /bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: hostlib
          hostPath:
            path: /usr/lib64
        - name: dev
          hostPath:
            path: /dev/
        - name: opt-bin
          hostPath:
            path: /opt/bin/
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: ceph-osd-pod
          image: cdxvirt/ceph-daemon:latest
          securityContext:
            privileged: true
          args: ["osd_controller"]
          env:
            - name: "DAEMON_VERSION"
              value: "cdxvirt/ceph-daemon:latest"
            - name: "DEBUG_MODE"
              value: "false"
            - name: "CRUSH_TYPE"
              value: "space"
            - name: "PGs_PER_OSD"
              value: "64"
            - name: "OSD_INIT_MODE"
              value: "minimal"
            - name: "MAX_OSDS"
              value: "1"
            - name: "KV_PORT"
              value: "2379"
            - name: "KV_TYPE"
              value: "etcd"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            exec:
              command:
              - /osd-ctl-liveprobe.sh
            timeoutSeconds: 5
          volumeMounts:
            - name: docker
              mountPath: /bin/docker
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: hostlib
              mountPath: /host/lib
            - name: dev
              mountPath: /dev/
            - name: opt-bin
              mountPath: /opt/bin/
            - name: localtime
              mountPath: /etc/localtime
