apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-osd
spec:
  template:
    metadata:
      labels:
        name: ceph-osd
    spec:
      hostNetwork: true
      nodeSelector:
        ceph_osd: "true"
      volumes:
        - name: docker
          hostPath:
            path: /bin/docker
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: ceph-dir
          hostPath:
            path: /var/lib/ceph/
        - name: libsystemd
          hostPath:
            path: /lib64/libsystemd.so.0
        - name: libdevmapper
          hostPath:
            path: /lib64/libdevmapper.so
        - name: libgcrypt
          hostPath:
            path: /lib64/libgcrypt.so
        - name: libgpg-error
          hostPath:
            path: /lib64/libgpg-error.so
        - name: dev
          hostPath:
            path: /dev/
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: disk-mapping
          hostPath:
            path: /opt/etc/port-mapping.json
        - name: paas-sds
          hostPath:
            path: /opt/etc/paas_sds.json
      containers:
        - name: ceph-osd-pod
          image: cdxvirt/ceph-daemon:1.12
          securityContext:
            privileged: true
          args: ["osd_controller"]
          env:
            - name: "DAEMON_VERSION"
              value: "cdxvirt/ceph-daemon:1.12"
            - name: "DEBUG_MODE"
              value: "false"
          volumeMounts:
            - name: docker
              mountPath: /bin/docker
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: ceph-dir
              mountPath: /var/lib/ceph/
            - name: libsystemd
              mountPath: /lib/x86_64-linux-gnu/libsystemd.so.0
            - name: libdevmapper
              mountPath: /lib/x86_64-linux-gnu/libdevmapper.so.1.02
            - name: libgcrypt
              mountPath: /lib/x86_64-linux-gnu/libgcrypt.so.20
            - name: libgpg-error
              mountPath: /lib/x86_64-linux-gnu/libgpg-error.so.0
            - name: dev
              mountPath: /dev/
            - name: localtime
              mountPath: /etc/localtime
            - name: disk-mapping
              mountPath: /disk-mapping.json
            - name: paas-sds
              mountPath: /paas_sds.json
          ports:
            - containerPort: 6701
              hostPort: 6701
