apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-mon
  labels:
    name: ceph-mon
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: ceph-mon
    spec:
      hostNetwork: true
      nodeSelector:
        cdxvirt/ceph_mon: "true"
      volumes:
        - name: cephconfig
          hostPath:
            path: /var/lib/ceph
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: ceph-mon-pod
          image: cdxvirt/ceph-daemon:daemon-10.2.6-1
          imagePullPolicy: IfNotPresent
          args: ["mon"]
          env:
            - name: "CEPH_PUBLIC_NETWORK"
              value: "192.168.32.0/23"
            - name: "CEPH_CLUSTER_NETWORK"
              value: "192.168.32.0/23"
            - name: "K8S_NETWORK"
              value: "192.168.32.0/23"
            - name: "DEBUG_MODE"
              value: "false"
            - name: "KV_TYPE"
              value: "etcd"
            - name: "KV_PORT"
              value: "2379"
            - name: "NETWORK_AUTO_DETECT"
              value: "5"
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            exec:
              command:
              - /cdxvirt/mon-liveprobe.sh
            timeoutSeconds: 5
          volumeMounts:
            - name: cephconfig
              mountPath: /var/lib/ceph
            - name: localtime
              mountPath: /etc/localtime
