apiVersion: v1
kind: ReplicationController
metadata:
  name: ceph-mon
  labels:
    name: ceph-mon
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: ceph-mon
    spec:
      hostNetwork: true
      nodeSelector:
        ceph_mon: "true"
      volumes:
        - name: cephconfig
          hostPath:
            path: /var/lib/ceph
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: ceph-mon-pod
          image: cdxvirt/ceph-daemon:1.12
          args: ["mon"]
          env:
            - name: "CEPH_PUBLIC_NETWORK"
              value: "172.18.0.0/24"
            - name: "CEPH_CLUSTER_NETWORK"
              value: "172.17.0.0/24"
            - name: "DEBUG_MODE"
              value: "false"
          volumeMounts:
            - name: cephconfig
              mountPath: /var/lib/ceph
            - name: localtime
              mountPath: /etc/localtime
          ports:
            - containerPort: 6700
              hostPort: 6700
