kind: ReplicationController
apiVersion: v1
metadata:
  name: mon-controller
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: mon-controller
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: mon-controller-pod
          image: cdxvirt/ceph-daemon:latest
          imagePullPolicy: IfNotPresent
          args: ["cdx_controller"]
          env:
            - name: "CEPH_PUBLIC_NETWORK"
              value: "192.168.32.0/23"
            - name: "CEPH_CLUSTER_NETWORK"
              value: "192.168.32.0/23"
            - name: "K8S_NETWORK"
              value: "192.168.32.0/23"
#            - name: "DEBUG"
#              value: "verbose"
            - name: "CDX_ENV"
              value: "true"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
