kind: ReplicationController
apiVersion: v1
metadata:
  name: mon-controller
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: mon-controller
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
      containers:
        - name: mon-controller-pod
          image: cdxvirt/ceph-daemon:latest
          args: ["mon_controller"]
          env:
            - name: "CEPH_PUBLIC_NETWORK"
              value: "172.18.0.0/24"
            - name: "CEPH_CLUSTER_NETWORK"
              value: "172.17.0.0/24"
            - name: "K8S_NETWORK"
              value: "172.17.0.0/24"
            - name: "DEBUG_MODE"
              value: "false"
            - name: "MAX_MONS"
              value: "3"
            - name: "KV_PORT"
              value: "2379"
            - name: "KV_TYPE"
              value: "etcd"
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
