apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ceph-mgr
  labels:
    name: ceph-mgr
  namespace: ceph
spec:
  template:
    metadata:
      labels:
        name: ceph-mgr
    spec:
      hostNetwork: true
      nodeSelector:
        cdx/ceph-mgr: "true"
      volumes:
        - name: cephlog
          hostPath:
            path: /var/log/ceph
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: dev
          hostPath:
            path: /dev/
      containers:
        - name: ceph-mgr-pod
          image: cdxvirt/ceph-daemon:latest
          securityContext:
            privileged: true
          args: ["mgr"]
          env:
            - name: "CDX_ENV"
              value: "true"
          volumeMounts:
            - name: cephlog
              mountPath: /var/log/ceph
            - name: localtime
              mountPath: /etc/localtime
            - name: dev
              mountPath: /dev/
